steps:
- name: 'sglahn/platformio-core:3.6.0'  
  dir: .
  args: ['run']  
artifacts: 
  objects: 
    location: 'gs://$PROJECT_ID-firmwares/$TAG_NAME'
    paths: ['/workspace/.pioenvs/esp32/firmware_esp32.bin']